name: hedis-streams
version: "0.2.0.0"
author: Diamondy4
maintainer: Diamondy4@hotmail.com
#license: UnspecifiedLicense

extra-source-files:
  - CHANGELOG.md

dependencies:
  - base >= 4.14 && <= 5
  - hedis
  - bytestring
  - optics-core

default-extensions:
  - OverloadedStrings
  - OverloadedLabels
  - TypeApplications
  - DataKinds
  - FlexibleContexts
  - FlexibleInstances
  - DeriveGeneric
  - DuplicateRecordFields
  - LambdaCase
  - DeriveAnyClass
  - DerivingStrategies
  - NamedFieldPuns
  - RecordWildCards
  - ImportQualifiedPost

ghc-options:
  - -Wall
  - -Wincomplete-patterns
  - -Wno-unticked-promoted-constructors

internal-libraries:
  hedis-streams-core:
    exposed: true
    visibility: public
    source-dirs: lib/hedis-streams-core
    dependencies:
      - mtl
  hedis-streams-streamly:
    exposed: true
    visibility: public
    source-dirs: lib/hedis-streams-streamly
    dependencies:
      - hedis-streams-core
      - streamly
      - monad-control
      - exceptions
      - transformers-base
  hedis-streams-streamly-store:
    exposed: true
    visibility: public
    source-dirs: lib/hedis-streams-streamly-store
    dependencies:
      - hedis-streams-core
      - hedis-streams-streamly
      - streamly
      - store
      - hashable
  hedis-streams-streamly-aeson:
    exposed: true
    visibility: public
    source-dirs: lib/hedis-streams-streamly-aeson
    dependencies:
      - hedis-streams-core
      - hedis-streams-streamly
      - streamly
      - exceptions
      - aeson
      - hashable
