name: redis-streamly
version: "0.1.0.0"
author: Diamondy4
maintainer: Diamondy4@hotmail.com
license: UnspecifiedLicense

extra-source-files:
  - CHANGELOG.md
dependencies:
  - base >= 4.14 && <= 5
  - hedis
  - streamly
  - bytestring
  - monad-control
  - exceptions
  - transformers-base
default-extensions:
  - OverloadedStrings
  - FlexibleContexts
  - FlexibleInstances

library:
  source-dirs: src
